export { default as Bar } from './bar'
// export { default as Desktop } from './desktop'
export { default as BarRoundedCorners } from './bar/roundedcorners'
export { default as Overview } from './overview'
export { default as PowerMenu } from './powermenu'
export { default as Verification } from './powermenu/Verification'
export { default as Indicators } from './indicators'
export { default as Launcher } from './launcher'
export { default as Notifications } from './notifications'

export { setupMenu } from './dropdownmenu'
