import { Theme, WP, lightColors } from '../settings/theme.js'

export default [
  Theme({
    name: 'Colony',
    icon: '󰄛',
    'theme.accent.accent': '$blue',
    'desktop.wallpaper.img': WP + 'colony-wallpaper-edit.png',
  }),
  Theme({
    name: 'Yokopi',
    icon: '',
    'desktop.wallpaper.img': WP + 'yukopi-wallpaper.png',
    'spacing': 11,
    'padding': 10,
    'radii': 12,
    'theme.accent.accent': '$yellow',
    'desktop.screen_corners': false,
    'desktop.clock.enable': false,
    'bar.separators': false,
    'bar.icon': '',
    'theme.bg': 'transparentize(#171717, 0.3)',
    'theme.widget.opacity': 95,
    'bar.flat_buttons': false,
  }),
  Theme({
    name: 'Yukopi Light',
    icon: '󰄛',
    'desktop.wallpaper.img': WP + 'yukopi-light-wallpaper.png',
    ...lightColors,
    'theme.widget.bg': '$accent',
    'theme.widget.opacity': 64,
  }),
  // Theme({
  //   name: 'Cabin',
  //   icon: '󰌪',
  //   'desktop.wallpaper.img': WP + ' cabin-wallpaper.jpg',
  //   'desktop.wallpaper.fg': '$bg_color',
  //   'desktop.screen_corners': false,
  //   'bar.style': 'separated',
  //   'theme.widget.bg': '$green',
  //   'theme.widget.opacity': 64,
  //   'desktop.drop_shadow': false,
  //   'border.width': 2,
  //   'border.opacity': 0,
  //   'theme.accent.accent': '$green',
  //   'theme.accent.gradient': 'to right, $accent, darken($accent, 6%)',
  //   'hypr.inactive_border': 'rgba(111111FF)',
  //   'bar.separators': false,
  // }),
  Theme({
    name: 'Cabin',
    icon: '󰌪',
    'desktop.wallpaper.img': WP + 'cabin-wallpaper-edit.jpg',
    'theme.accent.accent': '$green',
    'theme.accent.gradient': 'to right, $accent, darken($accent, 6%)',
    'theme.widget.opacity': 64,
    'border.opacity': 0,
    'bar.icon': '󰌪',
  }),
  Theme({
    name: 'NixOS',
    icon: '',
    'desktop.wallpaper.img': WP + 'nixos-wallpaper.png',
    'theme.accent.accent': '$blue',
    'theme.accent.gradient': 'to right, $accent, darken($accent, 14%)',
    'theme.widget.opacity': 92,
    'border.opacity': 86,
    'theme.bg': 'transparentize(#171717, 0.3)',
    'bar.icon': '',
    'radii': 0,
  }),
]
